### ISSUE TITLE
EPIC: Structure GitHub Issues, Wiki pages, Projects, and Milestones to startup transaction web app development

### ISSUE THREAD

**Issue by MarkWiltberger** [MarkWiltberger/portfolio-overview#1]
**Dependency**

**Overview**
We need to set up the GitHub project management system for our project. It needs to be useable and clear to someone else.
I have looked into Jira and Confluence. It may be simpler and more transparent to use GitHub

**Action Items**
Some issues:
- [ ] Some elements of the GitHub system do not go across repositories. Investigate whether there should only be one repository.
- [ ] Look at the epic created in Jira and recreate the steps here.
    - [ ] it should provide step-by-step actions to get development up and running.
- [ ] One of the questions is do we want to have the Issues transparent for all projects and for all people.
- [ ] Take another look at the pros/cons of GitHub vs Jira/Confluence for the issue tracking system.

**Resources/Instructions**
